kr270:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_a1_position_controller:
    type: effort_controllers/JointPositionController
    joint: a1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_a2_position_controller:
    type: effort_controllers/JointPositionController
    joint: a2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_a3_position_controller:
    type: effort_controllers/JointPositionController
    joint: a3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_a4_position_controller:
    type: effort_controllers/JointPositionController
    joint: a4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_a5_position_controller:
    type: effort_controllers/JointPositionController
    joint: a5
    pid: {p: 100.0, i: 0.01, d: 10.0}