kr270:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_a1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a1
    pid: {p: 100.0, i: 1.0, d: 10.0, i_clamp_max: 15.0, i_clamp_min: -15.0}
  joint_a2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a2
    pid: {p: 150.0, i: 1.0, d: 10.0, i_clamp_max: 15.0, i_clamp_min: -15.0}
  joint_a3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a3
    pid: {p: 100.0, i: 1.0, d: 10.0, i_clamp_max: 15.0, i_clamp_min: -15.0}
  joint_a4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a4
    pid: {p: 100.0, i: 1.0, d: 10.0, i_clamp_max: 15.0, i_clamp_min: -15.0}
  joint_a5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a5
    pid: {p: 100.0, i: 1.0, d: 10.0, i_clamp_max: 15.0, i_clamp_min: -15.0}